config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts
  devise_for :users 
  get 'static_pages/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'admins/index', controller: "admins#index", as: 'admins'
  
  resource :admin do
    resources :abouts
    resources :services
    resources :portfolios
  end
     

  root 'static_pages#index'; 
  
   
    scope module: 'static_pages' do

      namespace :index, path: 'static_pages' do
        get 'services'
        get 'portfolio'
        get 'contact'
        get 'home'
       end

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_one_attached :image
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy, :portfolio]
  before_action :authenticate_user!
  # GET /portfolios
  # GET /portfolios.json
  def index
   #   @portfolios = Portfolio.all
  end
  
 # def portfolio
  #  @portfolios = Portfolio.all
  #end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:titel, :description, :image, :portfolio_image)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titel %>
    <%= form.text_field :titel %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :portfolio_image %>
    <%= form.text_field :portfolio_image %>
  </div>
  <div class="field">
    <%= form.label "Attach Image"%>
    <%= form.file_field :image%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<p id="notice"><%= notice %></p>

<div class= "col-lg-12">
<div class = "row">
    <% @portfolios.each do |portfolio| %>
        <div class="col-lg-3">
          <div class="card text-left">
             
            <%#=link_to (image_tag url_for(portfolio.image), class:"card-img-top"), portfolio   %>
              <div class="card-body">
                <h4 class=<%= portfolio.titel %>>Title</h4>
                <p class="card-text"><%= portfolio.description %></p>
              </div>
         </div>
        </div>
    <% end %>
  </div>
</div>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titel:</strong>
  <%= @portfolio.titel %>
</p>

<p>
  <strong>Description:</strong>
  <%= @portfolio.description %>
</p>
<%= image_tag @portfolio.image  %>
<p>
  <strong>Portfolio image:</strong>
  <%= @portfolio.portfolio_image %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>