config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts
  devise_for :users 
  get 'static_pages/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'admins/index', controller: "admins#index", as: 'admins'
  
  resource :admin do
    resources :abouts
    resources :services
    resources :portfolios
  end
     

  root 'static_pages#index'; 
  
   
    scope module: 'static_pages' do

      namespace :index, path: 'static_pages' do
        get 'services'
        get 'portfolio'
        get 'contact'
        get 'home'
       end

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update]
  before_action :authenticate_user!
  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end


  def about_list
    @abouts = About.all
  end
  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new 
  def new
    
  end
  

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json


  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:description, :social, :profile_Picture)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_abouts.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Social</th>
      <th>Profile picture</th>
     
    </tr>
  </thead>

  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= about.description %></td>
        <td><%= about.social %></td>
        <td><%= about.profile_Picture %></td>    
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/abouts/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :social %>
    <%= form.text_field :social %>
  </div>

  <div class="field">
    <%= form.label :profile_Picture %>
    <%= form.text_field :profile_Picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @about.description %>
</p>

<p>
  <strong>Social:</strong>
  <%= @about.social %>
</p>

<p>
  <strong>Profile picture:</strong>
  <%= @about.profile_Picture %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>